name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/library-management-api:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2_user
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          # Navigate to project directory
          mkdir -p ~/library-api
          cd ~/library-api

          # Create docker-compose.yml
          cat > docker-compose.yml << EOF
          version: '3'
          services:
            web:
              image: ${{ secrets.DOCKERHUB_USERNAME }}/library-management-api:latest
              ports:
                - "5000:5000"
              restart: always
          EOF

          # Pull latest image and restart container
          docker-compose pull
          docker-compose down
          docker-compose up -d
